### ISSUE TITLE
pytz dependency missing in current pypi latest version (0.6.1)

### ISSUE THREAD

**Issue by nastasi** [adriank/ObjectPath#96]
This is what I can see on my console without installing pytz, probably there is
a missing dependency in setup.py file, cheers.
```
(venv) $ objectpath '$' data/nepal_exposure.json.in
Traceback (most recent call last):
  File "/home/nastasi/venv_objectslt/lib/python3.6/site-packages/objectpath/shell.py", line 19, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nastasi/venv_objectslt/bin/objectpath", line 7, in <module>
    from objectpath.shell import main
  File "/home/nastasi/venv_objectslt/lib/python3.6/site-packages/objectpath/shell.py", line 21, in <module>
    if os.isatty(sys.stdin.fileno()) and sys.stdout.isatty():
NameError: name 'os' is not defined
(venv) $ python --version
Python 3.6.9
```

**Comment by adriank** [comment]
PR welcomed. :)

Greetings,
Adrian Kalbarczyk

https://kalbarczyk.co | https://devyard.io

**Comment by nastasi** [comment]
Done lazy man.

**Comment by adriank** [comment]
Merged hard working man.
